services:
  # Database
  db:
      image: "postgres:16-alpine"
      container_name: "sk-db"
      restart: unless-stopped
      environment:
        LC_ALL: C.UTF-8
        POSTGRES_USER: stimmungskalender
        POSTGRES_PASSWORD: stimmungskalender
        POSTGRES_DB: stimmungskalender
      volumes:
        - "db:/var/lib/postgresql/data"

  # Django app
  app:
      image: "rain0r/stimmungskalender-app"
      container_name: "sk-app"
      platform: ${BUILD_PLATFORM:-}
      build:
        dockerfile: ./docker/app/Dockerfile
        args:
          DATABASE_URL: "pgsql://stimmungskalender:stimmungskalender@db/stimmungskalender"
          LOG_FILE_PATH: /logs/stimmungskalender.log
          STATIC_ROOT: /srv/www/stimmungskalender/static/
      environment:
        ALLOWED_HOSTS: "127.0.0.1,localhost" # Add your Stimmungskalender-URL here
        DATABASE_URL: "pgsql://stimmungskalender:stimmungskalender@db/stimmungskalender"
        FIRST_DAY_OF_WEEK: 1
        LANGUAGE_CODE: de-de
        LOG_FILE_PATH: /logs/stimmungskalender.log
        SECRET_KEY: "PLEASE-CHANGE-ME"
        STATIC_ROOT: /srv/www/stimmungskalender/static/
        TIME_ZONE: Europe/Berlin
      ports:
        - "7890:8000"
      volumes:
        - "static:/srv/www/stimmungskalender/static"
        - "./logs:/logs"
      depends_on:
        - db

volumes:
  db:
  static:
