services:
  # Database
  db:
      image: "postgres:16-alpine"
      container_name: "sk-db"
      restart: unless-stopped
      environment:
        LC_ALL: C.UTF-8
        POSTGRES_USER: stimmungskalender
        POSTGRES_PASSWORD: stimmungskalender
        POSTGRES_DB: stimmungskalender
      volumes:
        - "db:/var/lib/postgresql/data"

  # Django app
  app:
      image: "rain0r/stimmungskalender-app"
      container_name: "sk-app"
      build:
        dockerfile: ./docker/app/Dockerfile
        platforms:
          - "linux/amd64"
          - "linux/arm64"
          - "linux/ppc64le"
          - "linux/s390x"
          - "linux/arm/v7"
          - "linux/arm/v6"
        args:
          DATABASE_URL: "pgsql://stimmungskalender:stimmungskalender@db/stimmungskalender"
          LOG_FILE_PATH: /logs/stimmungskalender.log
          SECRET_KEY: "PLEASE-CHANGE-ME"
          STATIC_ROOT: /srv/www/stimmungskalender/static/
      environment:
        ALLOWED_HOSTS: "127.0.0.1,localhost" # Add your Stimmungskalender-URL here
        DATABASE_URL: "pgsql://stimmungskalender:stimmungskalender@db/stimmungskalender"
        LOG_FILE_PATH: /logs/stimmungskalender.log
        SECRET_KEY: "PLEASE-CHANGE-ME"
        STATIC_ROOT: /srv/www/stimmungskalender/static/
        SESSION_COOKIE_SECURE: True
      ports:
        - "7891:8000"
      volumes:
        - "static:/srv/www/stimmungskalender/static"
        - "./logs:/logs"
      depends_on:
        - db

  # Nginx
  web:
      image: "rain0r/stimmungskalender-web"
      container_name: "sk-web"
      restart: unless-stopped
      build:
        dockerfile: ./docker/web/Dockerfile
        platforms:
          - "linux/amd64"
          - "linux/arm64"
          - "linux/ppc64le"
          - "linux/s390x"
          - "linux/arm/v7"
          - "linux/arm/v6"
      ports:
        - "7890:80"
      volumes:
        - "static:/srv/www/stimmungskalender/static"
      depends_on:
        - app

volumes:
  db:
  static:
