version: '3.9'

services:
  # Database
  db:
      image: "postgres:15-alpine"
      restart: unless-stopped
      env_file: ./docker/db/env
      ports:
        - "8081:5432"
      volumes:
        - "db:/var/lib/postgresql/data"

  # Django app
  app:
      env_file: ./docker/app/django-env-pgsql
      build:
        context: .
        dockerfile: ./docker/app/Dockerfile
      command: uwsgi
      expose:
        - "8000"
      ports:
        - "8000:8000"
      volumes:
        - "static:/srv/www/stimmungskalender/static"
      depends_on:
        - db

  # Nginx
  web:
      build:
        context: ./
        dockerfile: ./docker/web/Dockerfile
      ports:
        - "8080:80"
      volumes:
        - "static:/srv/www/stimmungskalender/static"
      depends_on:
        - app

volumes:
  db:
  static:
