[tool.poetry]
name = "stimmungskalender"
version = "1.7.0"
description = "Self-hosted mood calendar"
authors = ["Rainer Hihn <hihn.rainer@gmail.com>"]
license = "AGPL-3.0-only"

[tool.poetry.dependencies]
python = "^3.9"
Django = "^4.1"
dj-database-url = "^1.2.0"
dj-rest-auth = "^2.2.7"
django-cache-url = "^3.4.4"
django-cors-headers = "^3.13.0"
django-registration = "^3.3"
django-rosetta = "^0.9.8"
djangorestframework-dataclasses = "^1.2.0"
djangorestframework-simplejwt = "^5.2.2"
djangorestframework = "^3.14.0"
drf-spectacular = "^0.25.1"
ipython = "^8.10.0"
psycopg2 = "^2.9.5"
python-decouple = "^3.7"
django-bootstrap-v5 = "^1.0.11"
redis = "^4.4.2"

[tool.poetry.dev-dependencies]
black = "^23.1.0"
djlint = "^1.19.13"
ipdb = "^0.13.11"
django-stubs = {extras = ["compatible-mypy"], version = "^1.15.0"}
flake8-django = "^1.1.5"
types-pkg-resources = "^0.1.3"

[tool.poetry.group.dev.dependencies]
isort = "^5.12.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"