git[tool.poetry]
name = "stimmungskalender"
version = "1.4.0"
description = "Self-hosted mood calendar"
authors = ["Rainer Hihn <hihn.rainer@gmail.com>"]
license = "AGPL-3.0-only"

[tool.poetry.dependencies]
python = "^3.8"
Django = "^4.1"
dj-database-url = "^1.0.0"
dj-rest-auth = "^2.2.4"
django-cache-url = "^3.4.2"
django-cors-headers = "^3.13.0"
django-registration = "^3.3"
django-rosetta = "^0.9.8"
djangorestframework-dataclasses = "^1.1.1"
djangorestframework-simplejwt = "^5.2.0"
djangorestframework = "^3.14.0"
drf-spectacular = "^0.24.2"
ipython = "^8.5.0"
plotly = "^5.10.0"
psycopg2 = "^2.9.3"
python-decouple = "^3.6"
django-bootstrap-v5 = "^1.0.11"

[tool.poetry.dev-dependencies]
black = "^22.8.0"
djlint = "^1.18.0"
ipdb = "^0.13.9"
mypy = "^0.981"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
